version: '2'
services:
  mujprojekt-mysql:
    image: mysql:latest
    container_name: mujprojekt-mysql
    ports:
      - 3333:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: mujprojekt
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 1234
    network_mode: bridge

  mujprojekt-webserver:
    image: phpdockerio/nginx:latest
    container_name: mujprojekt-webserver
    volumes_from:
      - mujprojekt-folder
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=mujprojekt.test
    network_mode: bridge
    links:
      - mujprojekt-php-fpm
    expose:
      - "9988"

  mujprojekt-php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        USER_NAME: ${USER}
    container_name: mujprojekt-php-fpm
    user: ${USER}
    volumes_from:
      - mujprojekt-folder
    volumes:
      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    network_mode: bridge
    links:
      - mujprojekt-mysql

  mujprojekt-folder:
    image: tianon/true
    container_name: mujprojekt-folder
    volumes:
      - "./:/var/www/mujprojekt"

volumes:
  mujprojekt-folder: